-- Seed data: sample races in the SP interior region
-- Note: These are fictional races for development purposes

INSERT INTO public.races (name, slug, date, start_time, city, state, address, latitude, longitude, distances, registration_price, registration_link, registration_deadline, prize_type, prize_details, route_description, organizer, description, status, rsvp_count, created_by, origin) VALUES

('Corrida Noturna Rio Preto', 'corrida-noturna-rio-preto', '2026-03-15', '19:00', 'São José do Rio Preto', 'SP', 'Represa Municipal, Av. Danilo Galeazzi', -20.8113, -49.3758, ARRAY['5k','10k'], '1º lote R$80, 2º lote R$100', 'https://example.com/inscricao1', '2026-03-10', 'trophy', 'Troféu para os 5 primeiros de cada categoria', 'Percurso plano ao redor da represa municipal', 'Assessoria Rio Preto Runners', 'A tradicional corrida noturna de Rio Preto está de volta! Percurso iluminado e plano, ideal para todos os níveis.', 'confirmed', 0, NULL, 'admin'),

('Meia Maratona de Votuporanga', 'meia-maratona-votuporanga', '2026-04-05', '06:30', 'Votuporanga', 'SP', 'Praça Fernando Costa, Centro', -20.4218, -49.9729, ARRAY['5k','10k','21k'], '1º lote R$100, 2º lote R$130', 'https://example.com/inscricao2', '2026-03-28', 'both', 'Premiação em dinheiro: R$1.000 (1º), R$500 (2º), R$300 (3º). Troféu até 5º lugar', 'Percurso com leves ondulações pelas ruas centrais da cidade', 'Prefeitura de Votuporanga', 'A maior prova de corrida de rua de Votuporanga. Percurso certificado pela CBAt.', 'confirmed', 0, NULL, 'admin'),

('5K Solidária Araçatuba', '5k-solidaria-aracatuba', '2026-03-22', '07:00', 'Araçatuba', 'SP', 'Parque Ecológico, Rua Cuiabá', -21.2089, -50.4328, ARRAY['5k'], 'R$50 + 1kg de alimento', 'https://example.com/inscricao3', '2026-03-18', 'none', NULL, 'Percurso dentro do Parque Ecológico, totalmente plano', 'ONG Correr para Ajudar', 'Corrida beneficente com renda revertida para instituições de caridade locais.', 'confirmed', 0, NULL, 'admin'),

('Desafio Trail Catanduva', 'desafio-trail-catanduva', '2026-04-12', '06:00', 'Catanduva', 'SP', 'Fazenda Santa Clara, Rod. Washington Luís km 380', -21.1378, -48.9726, ARRAY['10k','21k'], 'R$120', 'https://example.com/inscricao4', '2026-04-05', 'money', 'R$2.000 (1º), R$1.000 (2º), R$500 (3º) - categorias masculino e feminino', 'Trilha com terreno misto, subidas e descidas em fazenda', 'Adventure Sports Catanduva', 'Para quem gosta de desafio! Prova de trail running com percurso técnico em meio à natureza.', 'confirmed', 0, NULL, 'admin'),

('Circuito de Corridas Fernandópolis - Etapa 1', 'circuito-corridas-fernandopolis-etapa-1', '2026-03-29', '07:30', 'Fernandópolis', 'SP', 'Ginásio de Esportes, Av. Litério Grecco', -20.2839, -50.2467, ARRAY['5k','10k'], 'R$60', 'https://example.com/inscricao5', '2026-03-25', 'trophy', 'Troféu para os 3 primeiros overall e por faixa etária', 'Percurso urbano passando pelos principais pontos da cidade', 'Secretaria de Esportes de Fernandópolis', 'Primeira etapa do Circuito Municipal de Corridas 2026.', 'confirmed', 0, NULL, 'admin'),

('Night Run Olimpia', 'night-run-olimpia', '2026-04-19', '20:00', 'Olímpia', 'SP', 'Thermas dos Laranjais, Av. do Folclore', -20.7368, -48.9163, ARRAY['5k'], 'R$90 (inclui acesso ao parque)', 'https://example.com/inscricao6', '2026-04-15', 'none', NULL, 'Percurso ao redor do complexo turístico com iluminação especial', 'Thermas dos Laranjais', 'Corrida noturna com clima de festa! Inclui acesso ao parque aquático no dia seguinte.', 'confirmed', 0, NULL, 'admin'),

('Maratona Regional do Noroeste Paulista', 'maratona-regional-noroeste-paulista', '2026-05-10', '05:30', 'São José do Rio Preto', 'SP', 'Centro de Convenções, Av. Alberto Andaló', -20.8200, -49.3800, ARRAY['5k','10k','21k','42k'], '21k: R$150, 42k: R$200', 'https://example.com/inscricao7', '2026-04-30', 'money', 'Maratona: R$5.000 (1º), R$3.000 (2º), R$1.500 (3º). Meia: R$2.000 (1º), R$1.000 (2º)', 'Percurso certificado pela CBAt, passando por avenidas principais com apoio completo', 'Associação de Atletismo do Noroeste Paulista', 'A maior prova de corrida de rua da região noroeste de SP. Percurso plano e rápido, ideal para buscar marcas pessoais.', 'confirmed', 0, NULL, 'admin'),

('Corrida do Trabalhador - Birigui', 'corrida-do-trabalhador-birigui', '2026-05-01', '07:00', 'Birigui', 'SP', 'Praça Cândido Rondon, Centro', -21.2883, -50.3400, ARRAY['5k','10k'], 'R$45', 'https://example.com/inscricao8', '2026-04-28', 'trophy', 'Troféu para os 5 primeiros de cada categoria', 'Percurso plano pelas ruas centrais de Birigui', 'Prefeitura de Birigui', 'Corrida especial do Dia do Trabalhador com percurso para toda a família.', 'confirmed', 0, NULL, 'admin'),

('Penápolis Run 10K', 'penapolis-run-10k', '2026-04-26', '06:30', 'Penápolis', 'SP', 'Avenida São José, Centro', -21.4173, -50.0766, ARRAY['5k','10k'], 'R$70', 'https://example.com/inscricao9', '2026-04-20', 'both', 'Dinheiro: R$500 (1º), R$300 (2º). Troféu até 5º lugar', 'Percurso com leves aclives na região central', 'Equipe Penápolis Runners', 'Prova competitiva com excelente estrutura e percurso desafiador.', 'confirmed', 0, NULL, 'admin'),

('Corrida da Primavera - Jales', 'corrida-da-primavera-jales', '2026-09-21', '07:00', 'Jales', 'SP', 'Praça da Matriz, Centro', -20.269, -50.546, ARRAY['5k','10k'], 'R$55', 'https://example.com/inscricao10', '2026-09-15', 'trophy', NULL, NULL, NULL, NULL),
('Corrida do Aniversário de Mirassol', 'corrida-aniversario-mirassol', '2026-06-14', '07:00', 'Mirassol', 'SP', 'Praça Cel. Joaquim de Toledo Piza, Centro', -20.8186, -49.5204, ARRAY['5k','10k'], 'R$65', 'https://example.com/inscricao11', '2026-06-10', 'trophy', 'Troféu para os 5 primeiros overall', 'Percurso pelas ruas do centro de Mirassol', 'Prefeitura de Mirassol', 'Comemoração do aniversário da cidade com corrida de rua para toda a comunidade.', 'confirmed', 0, NULL, 'admin'),

('10K Barretos Night', '10k-barretos-night', '2026-05-23', '19:30', 'Barretos', 'SP', 'Parque do Peão, Rod. Brigadeiro Faria Lima', -20.5573, -48.5678, ARRAY['5k','10k'], 'R$85', 'https://example.com/inscricao12', '2026-05-18', 'money', 'R$1.500 (1º), R$800 (2º), R$400 (3º) - masc e fem', 'Percurso ao redor do Parque do Peão com iluminação', 'Associação de Atletismo de Barretos', 'Corrida noturna no famoso Parque do Peão de Barretos.', 'confirmed', 0, NULL, 'admin');
